### ISSUE TITLE
Dark Theme and button

### ISSUE THREAD

**Issue by raviikushh** [justEhmadSaeed/landing-page-template#1]
Your website looks pretty good, but it will look awesome if we add dark theme and make some changes with button.
Also if we click on features it's not scrolling down to that part.
I can fix all this, assign me.

**Comment by justEhmadSaeed** [comment]
@raviikushh sure, it's done.

**Comment by raviikushh** [comment]
The changes that has been made are -
- Added the dark theme to the whole page
- made changes in the navbar by using buttons and hover effect
- made changes in the download cards using flex wrap and hover effects
- By clicking on the feature in the navbar it will smoothly scroll down to feature part
- made few changes in the footer too


![Screenshot (220)](https://github.com/justEhmadSaeed/landing-page-template/assets/77044005/5ae52ec6-8ae0-4ea3-8eb2-981c59e96038)
![Screenshot (222)](https://github.com/justEhmadSaeed/landing-page-template/assets/77044005/e90a060e-d3c1-45ee-95a4-512bc1fbc8ff)
![Screenshot (223)](https://github.com/justEhmadSaeed/landing-page-template/assets/77044005/d6d13c8d-8db5-4c67-b2b0-0ad9300706f1)
![Screenshot (218)](https://github.com/justEhmadSaeed/landing-page-template/assets/77044005/7b321910-8bb2-4f3d-b710-037a0b9059d0)
![Screenshot (219)](https://github.com/justEhmadSaeed/landing-page-template/assets/77044005/c6dd6533-7f08-4861-9c7a-25ab92b57545)
