### ISSUE TITLE
UI - Enhancements

### ISSUE THREAD

**Issue by rakshithapatel08** [justEhmadSaeed/landing-page-template#5]
hey, @justEhmadSaeed  , I have identified some issues while using the template in dark mode . 

- The `vercel app logo` must be changed to colour white when in dark mode for better visibility.
- The button containing the `github logo` did not match in terms of color with the wordings `Get it on github`.
- During hover of this button the logo must change to black and remain white not hovered.
- In the footer, the logos must be changed to white for better visibility.
- The outdated `twitter logo` must be changed.

![Screenshot (307)](https://github.com/justEhmadSaeed/landing-page-template/assets/109893073/e6a4afe4-ad30-47c4-b6b9-b9c83c33b18a)
![Screenshot (308)](https://github.com/justEhmadSaeed/landing-page-template/assets/109893073/813c66d7-a807-42f5-8f0d-684bda60cc56)
![Screenshot (310)](https://github.com/justEhmadSaeed/landing-page-template/assets/109893073/8d533004-f9e8-48b3-98cb-4f2f69013437)
![Screenshot (309)](https://github.com/justEhmadSaeed/landing-page-template/assets/109893073/d511b369-261e-4b2d-a0c1-96d77e8ffb1d)

I am working on these issues .

**Comment by rakshithapatel08** [comment]
@justEhmadSaeed ,I have raised a PR.

**Comment by justEhmadSaeed** [comment]
@rakshithapatel08 accepted.
